project:
  type: website
  output-dir: ../_site
  resources:
    - data/i18n.json
    - data/countries.min.json
    - data/education.min.json
    - data/profession.min.json
    - images/*.webp
    - choices-utils.js
    - cookie-consent.js
    - helpers.js
    - i18n.js
    - meta.js

citation:
  author: Ingo Giebel
  title: "Alpha Auriga: The genesis of Artificial Superintelligence (ASI)"
  url: "https://alpha-auriga.netlify.app/"

default-image-extension: webp

website:
  description: "Project Alpha Auriga explores a speculative timeline for the emergence of Artificial Superintelligence (ASI), its potential forms, and societal implications."
  favicon: images/logo.webp
  site-url: https://alpha-auriga.netlify.app/
  repo-url: https://github.com/IngoGiebel/project-genesis-asi
  repo-subdir: en
  repo-branch: trunk
  repo-actions: [ source, edit, issue ]
  page-navigation: true
  open-graph: true
  reader-mode: false
  cookie-consent:
    type: express
    style: headline
    prefs-text: "Cookie preferences"
  search:
    location: navbar
    type: overlay
    show-item-context: true
  navbar:
    pinned: true
    logo: images/logo.webp
    logo-alt: "Alpha Auriga company logo"
    left:
      - text: "Home"
        icon: house-door
        href: index.qmd
      - text: "Timeline"
        icon: clock
        href: timeline.qmd
      - text: "Survey"
        icon: patch-question
        href: survey.qmd
      - text: "Results"
        icon: bar-chart-line
        href: results.qmd
      - text: "Discussion"
        icon: chat-text
        href: discussion.qmd
      - text: "About"
        icon: info-circle
        href: about.qmd
      - text: "Bibliography"
        icon: book
        href: bibliography.qmd
    right:
      - text: "Cite"
        icon: quote
        href: "#citationModal"
      - text: "Language"
        icon: globe
        menu:
          - text: English
            href: /
          - text: Deutsch
            href: /de/
  page-footer:
    left: "Content on this site is licensed under <a href='https://creativecommons.org/licenses/by/4.0/' target='_blank' rel='noopener noreferrer'>CC BY 4.0</a>."

format:
  html:
    lang: en
    theme: cyborg
    css: styles.css
    respect-user-color-scheme: false
    toc: true
    code-link: true
    code-overflow: wrap
    fig-responsive: true
    self-contained-math: true
    include-after-body:
      - _chatbot-widget.html
      - _citation-modal.html
