project:
  type: website
  output-dir: ../_site/de
  resources:
    - data/i18n.json
    - data/countries.json
    - data/education.json
    - data/profession.json
    - images/*.webp
    - choices-utils.js
    - cookie-consent.js
    - helpers.js
    - i18n.js
    - meta.js

citation:
  author: Ingo Giebel
  title: "Alpha Auriga: Genesis der künstlichen Superintelligenz (KSI)"
  url: "https://alpha-auriga.netlify.app/de/"

default-image-extension: webp

website:
  description: "Projekt Alpha Auriga untersucht eine spekulative Zeitlinie für die Entstehung von künstlicher Superintelligenz (KSI), ihre potenziellen Formen und gesellschaftlichen Auswirkungen."
  favicon: images/logo.webp
  site-url: https://alpha-auriga.netlify.app/de/
  repo-url: https://github.com/IngoGiebel/project-genesis-asi
  repo-subdir: de
  repo-branch: trunk
  repo-actions: [ source, edit, issue ]
  page-navigation: true
  open-graph: true
  reader-mode: false
  cookie-consent:
    type: express
    style: headline
    prefs-text: "Cookie-Einstellungen"
  search:
    location: navbar
    type: overlay
    show-item-context: true
  navbar:
    pinned: true
    logo: images/logo.webp
    logo-alt: "Alpha Auriga Logo"
    left:
      - text: "Home"
        icon: house-door
        href: index.qmd
      - text: "Zeitlinie"
        icon: clock
        href: timeline.qmd
      - text: "Umfrage"
        icon: patch-question
        href: survey.qmd
      - text: "Ergebnisse"
        icon: bar-chart-line
        href: results.qmd
      - text: "Diskussion"
        icon: chat-text
        href: discussion.qmd
      - text: "Über"
        icon: info-circle
        href: about.qmd
      - text: "Bibliographie"
        icon: book
        href: bibliography.qmd
    right:
      - text: "Zitieren"
        icon: quote
        href: "#citationModal"
      - text: "Sprache"
        icon: globe
        menu:
          - text: English
            href: /
          - text: Deutsch
            href: /de/
  page-footer:
    left: "Die Inhalte dieser Seite sind unter <a href='https://creativecommons.org/licenses/by/4.0/deed.de' target='_blank' rel='noopener noreferrer'> CC BY 4.0</a> lizenziert."

format:
  html:
    lang: de
    theme: cyborg
    css: styles.css
    respect-user-color-scheme: false
    toc: true
    code-link: true
    code-overflow: wrap
    fig-responsive: true
    self-contained-math: true
    include-after-body:
      - _chatbot-widget.html
      - _citation-modal.html
