project:
  type: website
  resources:
    - choices-utils.js
    - cookie-consent.js
    - helpers.js
    - language-redirect.js
    - meta.js
    - data/countries.min.json
    - data/education.min.json
    - data/profession.min.json
    - i18n/de.json
    - i18n/en.json
    - images/*.webp

citation:
  author: Ingo Giebel
  title: "Alpha Auriga: The genesis of Artificial Superintelligence (ASI)"
  url: "https://alpha-auriga.netlify.app"

default-image-extension: webp

execute:
  freeze: auto

editor:
  visual: false

website:
  description: "Project Alpha Auriga explores a speculative timeline for the emergence of Artificial Superintelligence (ASI), its potential forms, and societal implications."
  favicon: images/logo.webp
  repo-url: https://github.com/IngoGiebel/project-genesis-asi
  repo-branch: trunk
  repo-actions: [ source, edit, issue ]
  page-navigation: true
  open-graph: true
  reader-mode: false
  cookie-consent:
    type: express
    style: headline
    version: 1
  search:
    location: navbar
    type: overlay
    show-item-context: true
  navbar:
    pinned: true
    logo: images/logo.webp
    logo-alt: "Alpha Auriga company logo"
    left:
      - text: "{{< i18n nav.home >}}"
        icon: house-door
        href: index.qmd
      - text: "{{< i18n nav.timeline >}}"
        icon: clock
        href: timeline.qmd
      - text: "{{< i18n nav.survey >}}"
        icon: patch-question
        href: survey.qmd
      - text: "{{< i18n nav.results >}}"
        icon: bar-chart-line
        href: results.qmd
      - text: "{{< i18n nav.discussion >}}"
        icon: chat-text
        href: discussion.qmd
      - text: "{{< i18n nav.about >}}"
        icon: info-circle
        href: about.qmd
      - text: "{{< i18n nav.bibliography >}}"
        icon: book
        href: bibliography.qmd
    right:
      - text: "{{< i18n nav.cite >}}"
        icon: quote
        href: "#citationModal"
      - icon: globe
        menu:
          - text: English
            href: /
          - text: Deutsch
            href: /de/

  page-footer:
    left: "{{< i18n footer.license >}}"

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    code-link: true
    code-overflow: wrap
    fig-responsive: true
    self-contained-math: true
    include-after-body:
      - _chatbot-widget.html
      - _citation-modal.html

languages:
  - id: en
    lang: en
    main: true
    title: "Alpha Auriga"
    description: "Project Alpha Auriga explores a speculative timeline for the emergence of Artificial Superintelligence (ASI), its potential forms, and societal implications."
  - id: de
    lang: de
    title: "Alpha Auriga"
    description: "Projekt Alpha Auriga untersucht eine spekulative Zeitlinie für die Entstehung von künstlicher Superintelligenz (KSI), ihre potenziellen Formen und gesellschaftlichen Auswirkungen."
