project:
  type: website

bibliography: bibliography.bib
bibliographystyle: american-psychological-association

website:
  title: "Alpha Auriga"
  page-navigation: true
  back-to-top-navigation: true
  open-graph: true
  reader-mode: true
  cookie-consent: true
  search:
    location: navbar
    type: textbox
    show-item-context: true
  navbar:
    pinned: true
    logo: logo.png
    logo-alt: "Alpha Auriga company logo"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    respect-user-color-scheme: true
    theme: cyborg
    css: styles.css
    toc: true
    code-link: true
    code-overflow: wrap
    fig-responsive: true

editor:
  visual: false
