project:
  type: website

bibliography: bibliography.bib
bibliographystyle: american-psychological-association

website:
  repo-url: https://github.com/IngoGiebel/project-genesis-asi
  repo-branch: trunk
  repo-actions: [source, edit, issue]
  page-navigation: true
  open-graph: true
  reader-mode: true
  cookie-consent: true
  search:
    location: navbar
    type: overlay
    show-item-context: true
  navbar:
    pinned: true
    logo: logo.png
    logo-alt: "Alpha Auriga company logo"
    left:
      - about.qmd
  page-footer:
    left: "Content on this site is licensed under <a href='https://creativecommons.org/licenses/by/4.0/' target='_blank' rel='noopener noreferrer'>CC BY 4.0</a>."

format:
  html:
    respect-user-color-scheme: true
    theme: cyborg
    css: styles.css
    toc: true
    code-link: true
    code-overflow: wrap
    fig-responsive: true

editor:
  visual: false
