project:
  type: website

citation:
  author: Ingo Giebel
  title: "Alpha Auriga: The genesis of Artificial Superintelligence (ASI)"
  url: "https://alpha-auriga.netlify.app"

resources:
  - choices-utils.js
  - cookie-consent.js
  - helpers.js
  - meta.js
  - data/countries.min.json
  - data/education.min.json
  - data/profession.min.json
  - images/*.webp

default-image-extension: webp

website:
  description: "Project Alpha Auriga explores a speculative timeline for the emergence of Artificial Superintelligence (ASI), its potential forms, and societal implications."
  repo-url: https://github.com/IngoGiebel/project-genesis-asi
  repo-branch: trunk
  repo-actions: [ source, edit, issue ]
  page-navigation: true
  open-graph: true
  reader-mode: false
  cookie-consent:
    type: express
    style: headline
    version: 1
  search:
    location: navbar
    type: overlay
    show-item-context: true
  navbar:
    pinned: true
    logo: images/logo.webp
    logo-alt: "Alpha Auriga company logo"
    left:
      - text: "Home"
        icon: house-door
        href: index.qmd
      - text: "Timeline"
        icon: clock
        href: timeline.qmd
      - text: "Survey"
        icon: patch-question
        href: survey.qmd
      - text: "Results"
        icon: bar-chart-line
        href: results.qmd
      - text: "Discussion"
        icon: chat-text
        href: discussion.qmd
      - text: "About"
        icon: info-circle
        href: about.qmd
      - text: "Bibliography"
        icon: book
        href: bibliography.qmd
    right:
      - text: "Cite"
        icon: quote
        href: "#citationModal"
  page-footer:
    left: "Content on this site is licensed under <a href='https://creativecommons.org/licenses/by/4.0/' target='_blank' rel='noopener noreferrer'>CC BY 4.0</a>."

format:
  html:
    respect-user-color-scheme: true
    theme: cyborg
    css: styles.css
    toc: true
    code-link: true
    code-overflow: wrap
    fig-responsive: true
    self-contained-math: true
    include-after-body:
      - _chatbot-widget.html
      - _citation-modal.html

execute:
  freeze: auto

editor:
  visual: false
