[build]
command = "quarto render"
publish = "_site"

[functions]
directory = "netlify/functions"

[build.environment]
GO_VERSION = "1.24"
SERVER_MODE = "prod"

[context.dev.environment]
SERVER_MODE = "dev"
