channels:
  - conda-forge
dependencies:
  - python >=3.12,<3.13
  - altair
  - google-cloud-firestore
  - ipykernel
  - IPython
  - jupyterlab
  - pandas
  - python-dateutil
  - scipy
  - seaborn
  - statsmodels
